### ISSUE TITLE
[tuna]404 at /github-release/FreeCAD/FreeCAD/LatestRelease

### ISSUE THREAD

**Issue by lindianfeng** [tuna/issues#1113]
#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：

#### 您的环境（Environment）
- 操作系统（OS Version）：
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by skyzh** [comment]
maybe dup of https://github.com/tuna/issues/issues/1087

**Comment by skyzh** [comment]
You can use `https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/github-release/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x64-installer.exe` 
or any other URL like `https://s3.jcloud.sjtu.edu.cn/899a892efef34b1b944a19981040f55b-oss01/github-release/FreeCAD/FreeCAD/releases/download/<tag>/<filename>` for rescue now. We will soon release GitHub-release registry at SJTUG mirror website (which allow you to browse) instead of using these s3 URLs.

**Comment by skyzh** [comment]
https://mirrors.sjtug.sjtu.edu.cn/github-release/FreeCAD/FreeCAD/releases/download/?mirror_intel_list is now available
