### ISSUE TITLE
CentOS仓库配置文件

### ISSUE THREAD

**Issue by JayceCao** [tuna/issues#144]
* 用以下内容将`/etc/yum.repos.d/CentOS-Base.repo`中的内容替换：
### 对于`CentOS 7`:
```sh
[base]
name=CentOS-$releasever - Base - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/os/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7

#released updates
[updates]
name=CentOS-$releasever - Updates - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/updates/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7

#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/extras/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7

#additional packages that extend functionality of existing packages
[centosplus]
name=CentOS-$releasever - Plus - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/centosplus/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus
gpgcheck=1
enabled=0
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7

#contrib - packages by Centos Users
[contrib]
name=CentOS-$releasever - Contrib - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/contrib/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=contrib
gpgcheck=1
enabled=0
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7
```

### 对于`CentOS 6`:
```sh
[base]
name=CentOS-$releasever - Base - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/os/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6

#released updates
[updates]
name=CentOS-$releasever - Updates - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/updates/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6

#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/extras/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6

#additional packages that extend functionality of existing packages
[centosplus]
name=CentOS-$releasever - Plus - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/centosplus/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus
gpgcheck=1
enabled=0
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6

#contrib - packages by Centos Users
[contrib]
name=CentOS-$releasever - Contrib - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/contrib/$basearch/
#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=contrib
gpgcheck=1
enabled=0
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6
```

* 其他版本只需将其中的大版本号改为相应版本号即可

**Comment by huiyiqun** [comment]
gpgkey不用改也最好不要改 用发行版里/etc下那个就好

JayceCao <notifications@github.com>于2016年11月6日周日 上午2:45写道：


   - 用以下内容将/etc/yum.repos.d/CentOS-Base.repo中的内容替换：

对于CentOS 7:

[base]
name=CentOS-$releasever - Base - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/os/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7
#released updates
[updates]
name=CentOS-$releasever - Updates - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/updates/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7
#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/extras/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7
#additional packages that extend functionality of existing packages
[centosplus]
name=CentOS-$releasever - Plus - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/centosplus/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus
gpgcheck=1
enabled=0
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7
#contrib - packages by Centos Users
[contrib]
name=CentOS-$releasever - Contrib - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/contrib/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=contrib
gpgcheck=1
enabled=0
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-7

对于CentOS 6:

[base]
name=CentOS-$releasever - Base - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/os/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6
#released updates
[updates]
name=CentOS-$releasever - Updates - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/updates/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6
#additional packages that may be useful
[extras]
name=CentOS-$releasever - Extras - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/extras/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras
gpgcheck=1
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6
#additional packages that extend functionality of existing packages
[centosplus]
name=CentOS-$releasever - Plus - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/centosplus/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus
gpgcheck=1
enabled=0
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6
#contrib - packages by Centos Users
[contrib]
name=CentOS-$releasever - Contrib - mirror.tuna.tsinghua.edu.cn
baseurl=https://mirror.tuna.tsinghua.edu.cn/centos/$releasever/contrib/$basearch/#mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=contrib
gpgcheck=1
enabled=0
gpgkey=https://mirror.tuna.tsinghua.edu.cn/centos/RPM-GPG-KEY-CentOS-6


   - 其他版本只需将其中的大版本号改为相应版本号即可

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tuna/issues/issues/144>, or mute the thread

**Comment by bigeagle** [comment]
Done~
