### ISSUE TITLE
broken package and installation failed

### ISSUE THREAD

**Issue by MithunHub** [tuna/issues#1484]
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php-pam : Depends: phpapi-20180731 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by ZenithalHourlyRate** [comment]
It seems that it is not a issue related to the mirror. After googling I found similar issues

https://askubuntu.com/questions/1338540/php-pam-depends-phpapi-20180731-but-it-is-not-installable
https://forum.openmediavault.org/index.php?thread/40511-error-installing-omv6-on-armbian-bullseye-php-pam-depends-phpapi-20180731-but-it/

You might follow the guide of the forum.

What's the OS version of your RPi and your intended OMV?

**Comment by MithunHub** [comment]
I tried that links, but failed. 

My RPi version is bullseye and OMV: the latest version. I assume some of the variable/links in the mirrors referring to broken packages.

**Comment by ZenithalHourlyRate** [comment]
> OMV: the latest version

It seems that you are using OMV `usul` (php-pam depends on phpapi-20180731), in the meanwhile the appropriate OMV for bullseye is OMV `shaitan` (php-pam depends on phpapi-20190902)

Note that phpapi is provided by debian instead of OMV.

This dependency can be found in  https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/packages/dists/usul/main/binary-armhf/Packages and 
https://mirrors.tuna.tsinghua.edu.cn/OpenMediaVault/packages/dists/shaitan/main/binary-armhf/Packages

You can substitute all the usul to shaitan in https://mirrors.tuna.tsinghua.edu.cn/help/openmediavault/ in you `/etc/apt/sources.list.d/openmediavault.list`
