### ISSUE TITLE
Request Mirror for Pytorch wheels

### ISSUE THREAD

**Issue by CDLuminate** [tuna/issues#363]
#### 项目名称与简介(Project Intro.)

PyTorch is a state-of-the-art machine learning / deep learning framework.

#### 上游地址与镜像方法(How to Mirror)

No FTP, no rsync. But we can simply parse the HTML source to obtain the whl URLs.
http://pytorch.org/

#### 其他信息(Other)
- 镜像大小(Mirror Size): 

Approximatelly, `(1: pip) x (2: osx, linux) x (4: cuda{8,9.0,9.1,none}) x (3: py27,py35,py36) * 500MB \approx 12GB`

**Comment by CDLuminate** [comment]
https://github.com/pytorch/pytorch/issues/990

**Comment by shankerwangmiao** [comment]
hello，我们已经在 anaconda 上线该 channel 

https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/

**Comment by soumith** [comment]
thank you very much for making mirror of pytorch channel, helps a lot of our users in China

**Comment by peterjc123** [comment]
What about the wheels (.whl) packages? Looks like there are only conda (.tar.bz2) packages in https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/. I know some of them may be available through PyPI, so we could use `pip install torch -i https://pypi.tuna.tsinghua.edu.cn/simple`. However, the packages for some specs are not available, like "https://download.pytorch.org/whl/cpu/torch-1.3.0%2Bcpu-cp36-cp36m-linux_x86_64.whl". Could you please cache them too, so that we can install them using sth like `pip install torch==1.3.0+cpu -f https://pypi.tuna.tsinghua.edu.cn/pytorch` and `pip install torch -f https://pypi.tuna.tsinghua.edu.cn/pytorch/cpu`?

**Comment by YouJiacheng** [comment]
Does anyone know if TUNA also mirror `+cpu` specs? SJTU mirror does mirror `+cpu` specs in https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html.

**Comment by vipcxj** [comment]
@YouJiacheng This mirror was last updated 7 months ago. I'm looking at the stuff in there and it's pretty old, is there a newer mirror?
