### ISSUE TITLE
[julia mirror] license/permission by setting BFSU as the upstream storage backend

### ISSUE THREAD

**Issue by johnnychen94** [tuna/issues#878]
As far as I understand the tuna policy it's okay to do so, but I'd like to make sure of it before we approaching this.

As the standard way of dispatching packages in Julia, the essence of the pkg server is a reverse-proxy server with fancy features tailored for Julia packaging usage. Julialang.org is planning to set up a pkg server in mainland China and serves it as `https://pkg.juliacn.com`(might change). __Will it be good to make BFSU mirror as one supplementary storage upstream?__ By doing this it can still get a relatively good performance when cache misses.

For clarification, although they share a large number of members, [Julialang.org](https://julialang.org/) is not a for-profit organization while [JuliaComputing, Inc.](https://juliacomputing.com/) is. On the other hand, [juliacn.com](https://cn.julialang.org/), registered under the name of @roger-luo, isn't yet a valid organization in China.

If possible, It would be good to reply also in English so that @staticfloat from Julialang.org can check this easily.

---

P.S. I failed to find any reference for this, the only piece of words I found relevant is "根据相关法律法规，本站不对欧盟用户提供服务" in the footer of [tsinghua mirror](https://mirrors.tuna.tsinghua.edu.cn/).

**Comment by Harry-Chen** [comment]
> Will it be good to make BFSU mirror as one supplementary storage upstream?

Seems no problem as long as you clearly state this on your website, etc. But I wonder what is the difference between directly using BFSU mirror and using your pkg server at `pkg.juliacn.com`?

> P.S. I failed to find any reference for this, the only piece of words I found relevant is "根据相关法律法规，本站不对欧盟用户提供服务" in the footer of Tsinghua mirror.

This has nothing to do with the license problem, only to avoid GDPR issues.

**Comment by johnnychen94** [comment]
> But I wonder what is the difference between directly using BFSU mirror and using your pkg server at pkg.juliacn.com?

Currently, there's not much user-side difference between the pkg server(`pkg.juliacn.com`) and the storage server (BFSU mirror).  In the future, the pkg server will provide many fancy features. _One of the biggest improvement will be partial downloading_, that you only need to download a small part of the data when (1) upgrading package versions (2) requiring only a subset of artifacts. All these partial data are computed by the pkg server in the runtime, so this feature won't be available for static https server like the BFSU mirror. I didn't do the experiments, but it's said that this makes the required data transfer 10-20x less.

Another major difference is, unlike the BFSU mirror, the pkg server [`pkg.julialang.org` is bundled together with the official Julia releases](https://github.com/JuliaLang/Pkg.jl/blob/531861f6677f434f6d594212d1085ac5bc309328/src/Pkg.jl#L23), which will redirect users from China to `pkg.juliacn.com`, which, if possible, will use BFSU mirror as one of the storage backends. By doing this, a `Chinese user` --fetch--> `pkg.julialang.org` --redirect--> `pkg.juliacn.com` --caching--> `BFSU` downloading chain is formed and thus automatically makes users from China benefit from the BFSU mirror without any settings.

It might also be worth noting that the pkg server [gathers some usage statistics](https://github.com/JuliaPackaging/PkgServer.jl/blob/c5a180ed441387018d5bb539055a71e03e0d998f/src/meta.jl#L105-L118) to improve the service quality.

> Seems no problem as long as you clearly state this on your website, etc.

@ViralBShah @staticfloat are julialang.org okay with this? We could try `https://us-east.storage.julialang.org` first and then see how adding BFSU as a supplementary improves usability.

**Comment by ViralBShah** [comment]
Also cc @stefankarpinski

**Comment by ViralBShah** [comment]
To clarify, the Julia project is part of NumFocus which is a US non-profit.

**Comment by StefanKarpinski** [comment]
Thank you for using English to allow us to follow along!

This makes sense to me from a technical perspective. Most traffic will be served by `pkg.juliacn.com` so this arrangement will offload much of the traffic send to the BFSU static mirror. When there is a cache miss at `pkg.juliacn.com` it will go to all the upstream storage servers, including the BFSU static mirror, which will be the closest and therefore almost certainly fastest, so data will generally be gotten from there by `pkg.juliacn.com` which will then cache it and serve it to people in China.

**Comment by staticfloat** [comment]
Yes, this seems like a good idea, from my perspective.

Our package serving topology is to have a few large "storage servers", which are more-or-less static archives that store _everything_; these are content-addressed archives of tarballs that store packages, artifacts, registry snapshots, etc...  We currently run one storage server `https://us-east.storage.julialang.org`, and I'm looking into setting up another in Asia, probably in either Singapore or South Korea.

We run many more, smaller "Pkg servers", which serve as local caches that clients connect to directly.  These servers run a local cache of resources that it collects from the storage servers, and speak a more complex protocol with the clients than the simple storage server protocol (which is a purely static server with optional extensions).  The Pkg servers will handle complex tasks such as calculating diffs for package upgrades, keeping the most commonly requested packages in the local cache, etc...  The storage servers simply scrape the ecosystem for resources, verify/normalize/compress them, and serve them upon request.

Using the BFSU server as an upstream storage server would be a nice addition to our setup in China, as we can then have our Pkg servers within China use the BFSU servers for most traffic, falling back to our out-of-country servers if the BFSU server does not yet have a resource.

**Comment by johnnychen94** [comment]
FYI, unlike `https://us-east.storage.julialang.org`, the BFSU mirror doesn't build tarballs for artifacts, instead, [it directly downloads them from the existing upstream](https://github.com/johnnychen94/StorageServer.jl/blob/6ea12a8b7b2435563fba834c7c7f5f9dd9fd8bcb/src/artifact.jl#L53). And I have plans to do the same for packages and registries.

**Comment by happyaron** [comment]
@johnnychen94 Would it be possible to use HTTP redirect instead? It would be better to just redirect user requests from pkg.juliacn.com to mirrors.bfsu.edu.cn because if you want to serve content with your server then it's better to pay for the storage by yourself, no matter whether you are non-for-profit.

**Comment by happyaron** [comment]
Also, most major open source projects are running HTTP redirectors if they have a centralized traffic distribution system, for example the Apache foundation, Fedora, CentOS, OSDN, etc. TUNA does not setup bare reverse proxy itself because it is meaningless, mostly a waste of resource, and I would like to kindly ask you to reconsider your options.

**Comment by johnnychen94** [comment]
Disclaimer: I'm not a member of julialang.org or JuliaComputing.com and I don't represent opinions of them. I'm replying as a common Julia user in the Chinese community.

> Would it be possible to use HTTP redirect instead?

Pkg server is the standard way to dispatch resources in Julia; it serves as a tailored caching layer to storage servers.

If the Julia service in BFSU is a pkg server, yes, we can do this in practice. However, this was requested in #798 and got rejected following the general maintenance rule to not set up any form of reverse-proxy-like services.

In #837, I have explored the possibility of setting up a *static* storage server here to make it compatible with the fallback option of Pkg, which is the package manager in Julia. It's proved to work out quite well these days. But storage servers are not designed as a standard way of resource dispatching; normal Julia users should not be aware of their existence. Simply redirecting requests to BFSU could be problematic for a long-term design.

> if you want to serve content with your server then it's better to pay for the storage by yourself,

Julialang has already set up a pkg server and also a storage server in Seoul for users in the Asia-Pacific region. It just doesn't work really well for users in mainland China. That's why we, as Julia users in the Chinese community, are finding supports from TUNA.

> TUNA does not setup bare reverse proxy itself because it is meaningless, mostly a waste of resource

Not sure if I understand the context here. Are you saying "if there is a well-running Julia service in mainland China, then TUNA doesn't need to provide another"? In this case, we're trying to set a well-running Julia service with the help of TUNA; we don't have one yet.

---

I want to re-emphasize it that I'm just a common Julia user in mainland China; here I'm playing more as a broker to get supports from both julialang.org and TUNA.

@happyaron Can you clarify your identity here? I'm now not sure what's the policy of TUNA on this issue.

**Comment by johnnychen94** [comment]
To summary up the differences between pkg server and storage server:

* Pkg server follows the standard protocol of resource dispatching in Julia; they are what users talk to. Storage server should be transparent to users, it happens to work equivalently as a feature-limited pkg server (but might change in the future)
* Pkg server (will) provides diff feature to reduce network traffics; it improves the service quality even if it runs in the storage server.

**Comment by johnnychen94** [comment]
And here's the progress as far as I've got updated:

- [x] run pkg server in mainland China (provided by SUSTech and maintained by julialang.org)
- [x] (optional) set pkg server as default option for users in mainland China (supported by julialang.org)
- [ ] upstream pkg server to a storage server in mainland China (what this issue is requesting)

**Comment by staticfloat** [comment]
Thanks @johnnychen94.  In case it's helpful, I am the infrastructure engineer who is setting up these servers worldwide for the Julia language Opensource project, although Johnny's explanations here are exactly what I would have said myself.

We have Pkg servers deployed around the globe.  These are small, intelligent servers that can do things like serve diffs of packages to clients that request them.  The Pkg servers are backed by larger, dumber, Storage servers that maintain full backups of the entire ecosystem and serve them out to Pkg servers when the Pkg servers need to service a client request but do not have a package in their cache.

We have recently deployed three small instances in China that are sponsored by SUST on the Huawei cloud.  These instances run Pkg servers.  They currently pull from our two storage servers that reside outside of China.

Due to the good work in setting up the static mirror at BFSU, and the high performance of the server, we thought it would be natural to use the BFSU mirror as a third upstream for the Pkg servers inside of China.  If this is acceptable to the maintainers here, we will do so, if not, we will continue to serve from our storage servers outside of China.

**Comment by happyaron** [comment]
We had a brief internal discussion and the short answer is that we would not like to participate as a static storage server behind your Pkg servers at this time.

Extended explanations:
We acknowledge that binary diffs and perhaps other features would benefit users in some degree, while in turn this is creating new burderns for organizing the mirror network. We have observed the difficult process of setting up the server at BFSU because of tooling issues, and it appears that this architecture is not friendly for either third-party mirrors or CDN services. From mirror admin's point of view, this solution doesn't sound sustainable to work in longer term when the infra is not fully operated by a single group of people, and we'd rather refrain from participating that much because of limited man power.

@johnnychen94 I'm a member of TUNA mirror admin team.

**Comment by johnnychen94** [comment]
Thanks for the explanation, in this case, we'll still redirect people to BFSU for a manual switch when the default pkg server doesn't perform well. Directly talking to the storage server( BFSU) will still function from what I've watched in Pkg; it is just should not be the standard protocol to users.

Does this decision affect the current Julia services, i.e., julia, julia-releases and julia-general.git?

**Comment by happyaron** [comment]
This should apply to all current Julia services that are under TUNA's administration.

The man power issue is not about immediate investment but rather potential cases in future operations. We can’t assure you that we always have spare hands to fix related issues in time, due to the nature of TUNA mirrors being mostly operated by students. Although we try hard to maintain our track record of responding in a timely manner, there are concerns when our service is potentially becoming a significant part of your traffic distribution network.

**Comment by johnnychen94** [comment]
Sorry that I didn't ask it clearly. I was asking if TUNA is still planning to serve the current Julia mirrors; if there're plans to close these services, please let us know ahead so that we have enough time to prepare for it.

**Comment by happyaron** [comment]
No we don't plan to shutdown current services, just rather not to opt-in to your centralized traffic distribution network.

**Comment by johnnychen94** [comment]
I'm closing this issue as this request is clearly rejected.

**Comment by StefanKarpinski** [comment]
We accept whatever decision is made by the TUNA staff. However, I did want to clarify that making the BSFU mirror and upstream to the three package servers in China would cause them to serve _less_ traffic than they do as a directly accessed server, as they are being used now. This is because they would only be used when a cache miss occurs on the three smaller servers—and so far, we've observed a 99% cache hit rate in these servers. The benefit of having the BSFU mirror as a fallback would be that cache misses would get served more quickly than from the US or Korea. Note that we did not plan to expose any users by default directly to BSFU mirror, so it would only see 1% of traffic served by the package servers based on the current cache hit rate.

**Comment by happyaron** [comment]
We serve more than a hundred different repositories on a cluster of several
servers, so that traffic isn't an issue for us but man power is actually
the most concerning resource.

Also if hit rate can be as high as 99% then a local storage backend might
not contribute enough value to the system, ;)

**Comment by StefanKarpinski** [comment]
We have some tentative plan to simplify the cron job that updates the static mirror, which would hopefully make things easier on your end. You’re absolutely right that with a 99% hit rate the fallback is not so necessary, although it does help users in China when they have a cache miss, which can otherwise be quite slow. We very much want to ensure a first class experience for Julia users there.

**Comment by StefanKarpinski** [comment]
Also, just in case it’s unclear, nothing would be required to be changed in any way on your end to satisfy this request: the existing mirror would stay exactly as it is, this request is just to ask permission to use the existing mirror as a fallback for the caching servers.

**Comment by johnnychen94** [comment]
I totally understand that current maintainers in TUNA are possibly not Julia users and don't want to invest that amount of time on maintaining one of the many mirrors. We are truly grateful that TUNA offers to host these Julia mirrors that solve a significant amount of package installing problems from users who don't know how to use proxies.

Speaking about sustainability, any possible service failure in the BFSU side won't cause much trouble to the pkg servers as they are also backed by the US and KR servers; pkg servers can perfectly handle such cases. Thus there won't be any urgent issues wrt this. I hope this can partly address some of your concerns.

If you still have concerns, I believe a disclaimer for unavailability can be totally acceptable to us as we don't request any further man-power investment to the pkg servers.

**Comment by StefanKarpinski** [comment]
Yes, this is an important point: we don't require any uptime guarantees of any kind. The design of this system is such that downtime on the part of the BFSU mirror is a non-issue—the caching servers will simply get resources from other servers that are further away (and thus slower) if the mirror is down.
