### ISSUE TITLE
aosp-latest.tar 有问题，请求帮助。

### ISSUE THREAD

**Issue by liboLiao** [tuna/issues#97]
你好，这个网址（ https://mirrors.tuna.tsinghua.edu.cn/help/AOSP/#section-1 ）下的https://mirrors.tuna.tsinghua.edu.cn/aosp-monthly/aosp-latest.tar 有问题。
下载aosp-latest.tar包用了5个多小时。

发现最致命的是根据网址教程：
````
tar xf aosp-latest.tar
cd AOSP   # 解压得到的 AOSP 工程目录  这时 ls 的话什么也看不到，因为只有一个隐藏的 .repo 目录
repo sync # 正常同步一遍即可得到完整目录 或 repo sync -l 仅checkout代码
````

出现了如下问题：

          fatal:git fetch-pack: expected shallow list
          fatal:The remote end hung up unexpectedly
          error: Cannot fetch platform/prebuilts/misc
          Fetching project platform/packages/apps/Tag
          error: Cannot fetch platform/prebuilts/gcc/drarwin/mips/mips64el-linux-android-4.9
          error: Exited sync due to fetch errors
          xxx@xxx-laptop:~/androidSource/AOSP$

每次repo sync都被这个error打断，不知道怎么解决,能帮助一下吗？万分谢谢。

**Comment by bigeagle** [comment]
似乎其他人没遇到这个问题？

**Comment by bigeagle** [comment]
你这样，把 `.repo/platform/prebuilts/gcc/drarwin/mips/mips64el-linux-android-4.9` 直接删了，再试

**Comment by liboLiao** [comment]
压缩包tar是24.99G， 经过checksum校验也是对的。用tar xf aosp-latest.tar解压缩之后：就是一个AOSP文件夹，文件夹下有一个.repo隐藏文件夹，里面包括 manifests , manifests.git, manifest.xml, project.list, peojects, project-objects, repo 没有你说的.repo/platform，不过project-objects下有platform文件夹，详细路径是.../AOSP/.repo/project-objects/platform/prebuilts/gcc/......但是直到gcc文件夹下ls一下，只有darwin-x86和linux-x86文件夹，却没有gcc/drarwin文件夹。
         不知道你们有人下载过这个包展开过吗？我下载下来计算了MD5校验和是正确的，说明我下载的包是完整和正确的，但是我展开后没有所指的目录。

**Comment by bigeagle** [comment]
我自己打的包，当然是测过的。
前两天更新了，下个新的吧。

**Comment by liboLiao** [comment]
好吧，多谢。

**Comment by TreeWu** [comment]
所以现在修复了没？兄弟

**Comment by senjoeson** [comment]
我现在也遇到了这样的问题 ，死活无法同步出结果来。这是我执行同步地日志
root@senjoeson-GL502VML:/home/senjoeson/WORKING_DIRECTORY/aosp# repo sync
Fetching project kernel/configs
Fetching project toolchain/binutils
Fetching project platform/external/chromium-libpac
Fetching project platform/external/gflags
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/chromium-libpac/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
Fetching projects:   0% (1/647)  Fetching project platform/external/python/pyparsing
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/gflags/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/toolchain/binutils/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/python/pyparsing/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/toolchain/binutils/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/chromium-libpac/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/gflags/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/python/pyparsing/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
error: Cannot fetch toolchain/binutils
Fetching project platform/external/python/proto-google-cloud-pubsub-v1
error: Cannot fetch platform/external/chromium-libpac
error: Cannot fetch platform/external/gflags
fatal: unable to access 'https://aosp.tuna.tsinghua.edu.cn/platform/external/python/proto-google-cloud-pubsub-v1/': Could not resolve host: aosp.tuna.tsinghua.edu.cn
error: Cannot fetch platform/external/python/pyparsing
remote: Counting objects: 1, done.        
remote: Total 1 (delta 0), reused 0 (delta 0)        
来自 https://aosp.tuna.tsinghua.edu.cn/platform/external/python/proto-google-cloud-pubsub-v1
 * [新标签]          android-p-preview-5 -> android-p-preview-5

error: Exited sync due to fetch errors
root@senjoeson-GL502VML:/home/senjoeson/WORKING_DIRECTORY/aosp# 

@bigeagle @liboLiao  @TreeWu   
你们当初是怎么解决的呢？

**Comment by sztsian** [comment]
@senjoeson 你的错误提示是 

> Could not resolve host: aosp.tuna.tsinghua.edu.cn

所以应该是你的网络问题。

**Comment by senjoeson** [comment]
@sztsian  老哥如果是 我的网络问题 但是为什么我能打开你们镜像站的官网呢?

**Comment by TreeWu** [comment]
检查一下虚拟机，看看是不是有两个盘？是不是有一个是和windows  的共享盘，我之前的问题就是因为这样所以检不出来

**Comment by senjoeson** [comment]
@TreeWu  感谢各位  好像确实网络配置有问题,.DNS服务解析确实很慢,昨晚我重新配置了 就好了 谢谢各位!!!  
@sztsian
